-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 00:13:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 00:33:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` FLOAT NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `tel` FLOAT NOT NULL,
  `dat_nasc` DATE NOT NULL,
  `idade` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `id` INT(11) NOT NULL,
  `id_aluno` INT(11) NOT NULL,
  `Aluno_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Turma_Aluno_idx` (`Aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Aluno`
    FOREIGN KEY (`Aluno_id`)
    REFERENCES `mydb`.`Aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `id` INT(11) NOT NULL,
  `id_aluno` INT(11) NOT NULL,
  `id_curso` INT(11) NOT NULL,
  `id_turma` INT(11) NOT NULL,
  `data_matricula` DATE NOT NULL,
  `Aluno_id` INT(11) NOT NULL,
  `Turma_id` INT(11) NOT NULL,
  `Curso_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Matricula_Aluno1_idx` (`Aluno_id` ASC) VISIBLE,
  INDEX `fk_Matricula_Turma1_idx` (`Turma_id` ASC) VISIBLE,
  INDEX `fk_Matricula_Curso1_idx` (`Curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno_id`)
    REFERENCES `mydb`.`Aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Turma1`
    FOREIGN KEY (`Turma_id`)
    REFERENCES `mydb`.`Turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_facilitador` INT(11) NOT NULL,
  `id_curso` INT(11) NOT NULL,
  `Curso_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Disciplina_Curso1_idx` (`Curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facilitador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facilitador` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `graduacao` VARCHAR(60) NOT NULL,
  `tel` FLOAT NULL,
  `Disciplina_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Disciplina_id`),
  INDEX `fk_Facilitador_Disciplina1_idx` (`Disciplina_id` ASC) VISIBLE,
  CONSTRAINT `fk_Facilitador_Disciplina1`
    FOREIGN KEY (`Disciplina_id`)
    REFERENCES `mydb`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
